name: $(Year:yy)$(DayOfYear)$(Rev:.r)
pool:
  vmImage: 'ubuntu-latest'

variables:
  version: 1.0
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.100
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: dotnet pack TcpMux/TcpMux.csproj -p:Version=$(version).$(Build.BuildNumber) -p:TargetFrameworks=netcoreapp3.1 -p:Configuration=$(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Build package'

- task: PublishBuildArtifacts@1
